### PR TITLE
Bugfix user page

### PR DESCRIPTION
**Pull request by gergelyNemeth**
I have fixed the broken link of the comments in user page, and made all tables sortable.
Check it!

### CODE REVIEW

**Comment by gergelyNemeth** [comment]
You are right, I'll test and fix it!

**Comment by adamFoldvari** [comment]
I tested it with my data, it seems to work properly.

**Comment by gergelyNemeth** [comment]
Yes, an error remained in the template of the user page. The arrows of the answer table sends wrong field name. I will fix it.

**Comment by gergelyNemeth** [comment]
I've made the fix, check it out.

**Pull request merged**
